const hobbiesList = [
    { id: 1, label: 'Soccer' },
    { id: 2, label: 'Gamer' },
    { id: 3, label: 'Climbing' },
    { id: 4, label: 'Fishing' },
    { id: 5, label: 'Photography' },
    { id: 6, label: 'Cooking' },
    { id: 7, label: 'Reading' },
    { id: 8, label: 'Music' },
    { id: 9, label: 'Dancing' },
    { id: 10, label: 'Streamer' },
    { id: 11, label: 'Youtuber' },
    { id: 12, label: 'Fitness' },
    { id: 13, label: 'Hiking' },
    { id: 14, label: 'Running' },
    { id: 15, label: 'Art' },
    { id: 16, label: 'Fashion' },
    { id: 17, label: 'Traveling' },
    { id: 18, label: 'Gardening' },
    { id: 19, label: 'Shopping' },
    { id: 20, label: 'Golf' },
    { id: 21, label: 'Tennis' },
    { id: 22, label: 'NBA' },
    { id: 23, label: 'Baseball' },
    { id: 24, label: 'Politics' },
    { id: 25, label: 'Volunteering' },
    { id: 26, label: 'Cars' },
    { id: 27, label: 'Motorcycles' },
    { id: 28, label: 'Skiing' },
    { id: 29, label: 'Marvels' },
    { id: 30, label: 'DC' },
    { id: 31, label: 'Anime' },
    { id: 32, label: 'Manga' },
    { id: 33, label: 'Kpop' },
    { id: 34, label: 'Kdrama' },
    { id: 35, label: 'Netflix' },
    { id: 36, label: 'Disney' },
    { id: 37, label: 'HBO' },
    { id: 38, label: 'Poetry' },
    { id: 39, label: 'Writing' },
    { id: 40, label: 'Blogging' },
    { id: 41, label: 'Playstation' },
    { id: 42, label: 'Xbox' },
    { id: 43, label: 'Nintendo' },
    { id: 44, label: 'PC' },
    { id: 45, label: 'Coding' },
    { id: 46, label: 'Tech' },
    { id: 47, label: 'Science' },
    { id: 48, label: 'Math' },
    { id: 49, label: 'History' },
    { id: 50, label: 'Economics' },
    { id: 51, label: 'Musician' },
    { id: 52, label: 'Poker' },
    { id: 53, label: 'Chess' },
    { id: 54, label: 'Puzzles' },
    { id: 55, label: 'Board Games' },
    { id: 56, label: 'Card Games' },
    { id: 57, label: 'Bowling' },
    { id: 58, label: 'Party' },
    { id: 59, label: 'Clubbing' },
    { id: 60, label: 'Designer' },
    { id: 61, label: 'Engineer' },
    { id: 62, label: 'Doctor' },
    { id: 63, label: 'Lawyer' },
    { id: 64, label: 'Teacher' },
    { id: 65, label: 'Student' },
    { id: 66, label: 'Entrepreneur' },
    { id: 67, label: 'Investor' },
    { id: 68, label: 'Finance' },
    { id: 69, label: 'Accounting' },
    { id: 70, label: 'Sales' },
    { id: 71, label: 'Marketing' },
    { id: 72, label: 'HR' },
    { id: 73, label: 'Consulting' },
    { id: 74, label: 'Real Estate' },
    { id: 75, label: 'Banking' },
    { id: 76, label: 'Insurance' },
    { id: 77, label: 'Retail' },
    { id: 78, label: 'Hospitality'},
    { id: 79, label: 'Agriculture'},
    { id: 80, label: 'Construction'},
    { id: 81, label: 'Transportation'},
    { id: 82, label: 'Manufacturing'},
    { id: 83, label: 'Mining'},
    { id: 84, label: 'Utilities'},
    { id: 85, label: 'Telecommunications'},
    { id: 86, label: 'Education'},
    { id: 87, label: 'Health Care'},
    { id: 88, label: 'Government'},
];

export default hobbiesList;